server:
  port: 8082

spring:
  application:
    name: agri-content-service
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/a_content?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true&useUnicode=true
    username: root
    password: qhq200110

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rfeng.agri.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
#      logic-delete-field: status
#      logic-delete-value: 0
#      logic-not-delete-value: 1

knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    swagger-model-name: 实体类列表
  openapi:
    title: 农业资讯模块接口文档
    description: 农业项目中资讯模块的所有接口定义，包括帖子、评论等
    version: 1.0.0
    contact:
      name: 开发者
      email: dev@example.com
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
  production: false  # 生产为true